### ISSUE TITLE
Antenna connector

### ISSUE THREAD

**Issue by Jap8nted** [GaudiLabs/OpenTheremin_V3_Shield#8]
Hi all, 

I live in Germany and have no idea how to find the antenna connectors. How are they called and where could I buy something like that.

Do you guys have any hint?

**Comment by GaudiLabs** [comment]
Hi
They are called banana connectors. you find them at reichelt. de

Urs

On 19 February 2022 12:12:46 CET, Jonatan Aponte ***@***.***> wrote:
>Hi all, 
>
>I live in Germany and have no idea how to find the antenna connectors. How are they called and where could I buy something like that.
>
>Do you guys have any hint?
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenTheremin_V3_Shield/issues/8
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
🧪 GaudiLabs LLC
Urs Gaudenz
Email: ***@***.***
www.gaudi.ch

**Comment by Jap8nted** [comment]
Thank you so much
